Go watch 3rd Vedio of udemy for it krishna nayak section 13

In [3]:
import pandas as pd 
df = pd.read_csv('data.csv')
df.head(5) ## first 5 rows of the data frame
##df.tail(5) ## last 5 rows of the data frame

       Name   Age      City   Salary  Experience
0  Himanshu  21.0    Bhopal  45000.0         1.0
1      John  25.0  New York  55000.0         3.0
2      Sara   NaN    London  62000.0         4.0
3      Aman  23.0       NaN  48000.0         2.0
4     Priya  27.0    Mumbai      NaN         5.0

In [4]:
df.describe() ## summary statistics of the data frame

             Age        Salary  Experience
count   8.000000      9.000000    9.000000
mean   26.000000  61000.000000    3.777778
std     3.338092  12559.856687    1.986063
min    21.000000  45000.000000    1.000000
25%    23.750000  52000.000000    2.000000
50%    26.000000  60000.000000    4.000000
75%    28.250000  70000.000000    5.000000
max    31.000000  82000.000000    7.000000

In [5]:
df.info() ## information about the data frame

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     str
 1   Age         8 non-null      float64
 2   City        9 non-null      str
 3   Salary      9 non-null      float64
 4   Experience  9 non-null      float64
dtypes: float64(3), str(2)
memory usage: 532.0 bytes

In [6]:
df.isnull()    
df.isnull().sum() ## count of missing values in each column

Name          0
Age           2
City          1
Salary        1
Experience    1
dtype: int64

In [ ]:
##handeling missing values
df.dropna(inplace=True) ## drop rows with missing values
df.fillna(0, inplace=True) ## fill missing values with 0
df.isnull().any(axis=1) ## check if there are any missing values in the data frame on column level

0    False
1    False
6    False
8    False
9    False
dtype: bool

In [16]:
##filling missing values with mean of the column 
df['SalaryFillna'] = df['Salary'].fillna(df['Salary'].mean()) ## create a new column SalaryFillna with filled missing values in Salary column with mean of the Salary column
##df['Salary'].fillna(df['Salary'].mean(), inplace=True) ## fill missing values in Salary column with mean of the Salary column
df

       Name   Age      City   Salary  Experience  SalaryFillna
0  Himanshu  21.0    Bhopal  45000.0         1.0       45000.0
1      John  25.0  New York  55000.0         3.0       55000.0
6     Emily  31.0   Chicago  82000.0         7.0       82000.0
8      Neha  24.0      Pune  52000.0         2.0       52000.0
9      Jack  28.0    Sydney  75000.0         6.0       75000.0

In [18]:
df = df.rename(columns = {'SalaryFillna':'SalaryFilled'}) ## rename the column SalaryFillna to SalaryFilled
df

       Name   Age      City   Salary  Experience  SalaryFilled
0  Himanshu  21.0    Bhopal  45000.0         1.0       45000.0
1      John  25.0  New York  55000.0         3.0       55000.0
6     Emily  31.0   Chicago  82000.0         7.0       82000.0
8      Neha  24.0      Pune  52000.0         2.0       52000.0
9      Jack  28.0    Sydney  75000.0         6.0       75000.0

In [23]:
##Change DataTypes 
df['Value_new'] = df['SalaryFilled'].astype(float) ## create a new column Value_new with changed data type of Value column to float
## astype not work  when there is NnN or any value not present so just use  fillna with mean or 0 to handle missing values before changing data type
df

       Name   Age      City   Salary  Experience  SalaryFilled  Value_new
0  Himanshu  21.0    Bhopal  45000.0         1.0       45000.0    45000.0
1      John  25.0  New York  55000.0         3.0       55000.0    55000.0
6     Emily  31.0   Chicago  82000.0         7.0       82000.0    82000.0
8      Neha  24.0      Pune  52000.0         2.0       52000.0    52000.0
9      Jack  28.0    Sydney  75000.0         6.0       75000.0    75000.0

In [24]:
df['new_Salary'] = df['Salary'].apply(lambda x:x*10/100)
df

,Name,Age,City,Salary,Experience,SalaryFilled,Value_new,new_Salary
0,Himanshu,21.0,Bhopal,45000.0,1.0,45000.0,45000.0,4500.0
1,John,25.0,New York,55000.0,3.0,55000.0,55000.0,5500.0
6,Emily,31.0,Chicago,82000.0,7.0,82000.0,82000.0,8200.0
8,Neha,24.0,Pune,52000.0,2.0,52000.0,52000.0,5200.0
9,Jack,28.0,Sydney,75000.0,6.0,75000.0,75000.0,7500.0

In [25]:
## grouping of objects 
grouped = df.groupby('City')['Salary'].mean() ## group the data frame by City column
grouped

City
Bhopal      45000.0
Chicago     82000.0
New York    55000.0
Pune        52000.0
Sydney      75000.0
Name: Salary, dtype: float64

In [27]:
## aggregate multiple fucntion 
agg = df.groupby('City')['Salary'].agg(['mean','sum','max','min'])
agg

             mean      sum      max      min
City
Bhopal    45000.0  45000.0  45000.0  45000.0
Chicago   82000.0  82000.0  82000.0  82000.0
New York  55000.0  55000.0  55000.0  55000.0
Pune      52000.0  52000.0  52000.0  52000.0
Sydney    75000.0  75000.0  75000.0  75000.0

In [28]:
## merging and joining of data frames
df1 = pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'],'Value2':[5,6,7]})

In [ ]:
## Merge Dataframe on a common key  How joins are same as SQL joins
pd.merge(df1,df2,on='Key',how='inner')

  Key  Value1  Value2
0   A       1       5
1   B       2       6